### ISSUE TITLE
Configuring more than one mapping results in a warning

### ISSUE THREAD

**Issue by psimonazzi** [dropwizard-bundles/dropwizard-configurable-assets-bundle#25]
When you set more than one mapping in the "mappings" config section, Dropwizard complains with a warning log because we are using the same servlet name for all mappings:
`Overriding the existing servlet registered with the name: assets`

But then all mappings work correctly.

**Comment by nbauernfeind** [comment]
Any chance you can provide a sample yaml or code-constructed configuration I can use to reproduce the behavior?

**Comment by psimonazzi** [comment]
We are mapping files in a "assets" dir inside the classpath (in a jar) to the "/" url, and a "static" dir in the filesystem (at the same level of the jar) to the "/static" url.

A minimal config:

```
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

assets:
  mappings:
    /assets: /
    /static: /static
  overrides:
    /static: ./static
```

In code we just call `bootstrap.addBundle(new ConfiguredAssetsBundle());`

This config generates the warning, but then behaviour is correct: files inside the jar are available at the "/" url, and files inside the dir are available at "/static".

The logs we see are:

```
Registering ConfiguredAssetBundle with name: assets for path /*
Registering ConfiguredAssetBundle with name: assets for path /static/*
Overriding the existing servlet registered with the name: assets
```
